<?php

/**
 * @file
 * Module file for ntb top 3.
 */

/**
 * Implements hook_block_info().
 */
function ntb_top_block_info() {
  $blocks['ntb_top_3'] = array(
    'info' => t('NTB top 3'),
  );

  $blocks['ntb_top_4'] = array(
    'info' => t('NTB top 4'),
  );

  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function ntb_top_block_configure($delta = '') {
  if ($delta == 'ntb_top_3' || $delta == 'ntb_top_4') {
    $form = [];
    $type = 'product_display';
    $query = [];

    $query = db_select('node', 'n')
      ->fields('n')
      ->condition('type', $type)
      ->condition('status', 1)
      ->execute()
      ->fetchAll();

    foreach ($query as $value) {
      $options[$value->nid] = $value->title;
    }

    $form['ntb_top_one'] = [
      '#type' => 'select',
      '#title' => t('NTB Top One'),
      '#options' => $options,
      '#default_value' => variable_get('ntb_top_one', NULL),
    ];

    $form['ntb_top_two'] = [
      '#type' => 'select',
      '#title' => t('NTB Top Two'),
      '#options' => $options,
      '#default_value' => variable_get('ntb_top_two', NULL),
    ];

    $form['ntb_top_three'] = [
      '#type' => 'select',
      '#title' => t('NTB Top Three'),
      '#options' => $options,
      '#default_value' => variable_get('ntb_top_three', NULL),
    ];

    $form['ntb_top_four'] = [
      '#type' => 'select',
      '#title' => t('NTB Top Four'),
      '#options' => $options,
      '#default_value' => variable_get('ntb_top_four', NULL),
    ];
  }

  return $form;
}

/**
 * Implements hook_block_save().
 */
function ntb_top_block_save($delta = '', $edit = array()) {
  if ($delta == 'ntb_top_3' || $delta == 'ntb_top_4') {
    $tops = ['ntb_top_four', 'ntb_top_three', 'ntb_top_two', 'ntb_top_one'];

    foreach ($tops as $top) {
      variable_set($top, $edit[$top]);
    }
  }
}

/**
 * Implements hook_block_view().
 */
function ntb_top_block_view($delta = '') {
  $block = [];

  switch ($delta) {
    case 'ntb_top_4':
      $block['content'] = ntb_top_build_display(4);
      break;

    case 'ntb_top_3':
      $block['content'] = ntb_top_build_display(3);
      break;
  }

  return $block;
}

/**
 * Build block display.
 *
 * @param int $num
 *   The total number to show.
 *
 * @return string
 *   HTML output of list items.
 */
function ntb_top_build_display($num) {
  $fields = ['ntb_top_three', 'ntb_top_two', 'ntb_top_one', 'ntb_top_four'];
  $nids = [];

  foreach ($fields as $field) {
    $nids[] = variable_get($field, NULL);
  }

  if ($num == 3) {
    array_pop($nids);
  }

  $nodes = node_load_multiple($nids);

  $node_displays = [];
  foreach ($nodes as $node) {
    $node_view = node_view($node, 'product_square', NULL);
    $node_displays[] = render($node_view);
  }
  $class = ['ntb-top'];
  $class[] = $num == 3 ? 'three-item' : 'four-item';

  $ouput = [
    '#theme' => 'item_list',
    '#items' => $node_displays,
    '#attributes' => [
      'class' => $class,
    ],
  ];



  return render($output);
}
