<?php

/**
 * @file
 * Code for the ajax add to cart enhancements.
 */

/**
 * Implements hook_preprocess_page().
 */
function dc_ajax_enhancements_preprocess_page(&$vars) {
  $block = module_invoke('dc_ajax_add_cart', 'block_view', 'ajax_shopping_cart');
  $vars['cart'] = $block;
  drupal_add_library('dc_ajax_enhancements', 'cart');
}

/**
 * Implements hook_theme().
 */
function dc_ajax_enhancements_theme() {
  return array(
    'dc_ajax_shopping_cart' => array(
      'variables' => array(
        'order' => NULL,
        'line_items' => NULL,
        'quantity' => NULL,
        'total' => NULL,
      ),
      'template' => 'templates/dc-ajax-enhancements-shopping-cart',
    ),
    'dc_ajax_add_to_cart_message' => array(
      'variables' => array(
        'line_item' => NULL,
        'product' => NULL,
        'quantity' => NULL,
      ),
      'template' => 'templates/dc-ajax-enhancements-add-to-cart-message',
    ),
  );
}

/**
 * Implements hook_preprocess_hook().
 */
function dc_ajax_enhancements_preprocess_dc_ajax_add_to_cart_message(&$vars) {
  $image_arr = $vars['product']->field_primary_image[LANGUAGE_NONE][0];
  [$image_alt, $image_title] = site_general_get_alt_title($image_arr, $vars->title);

  $img_array = array(
    '#theme' => 'image_style',
    '#style_name' => 'square_500x500',
    '#path' => $image_arr['uri'],
    '#alt' => $image_alt,
    '#title' => $image_title,
  );
  $vars['product_image'] = drupal_render($img_array);
}

/**
 * Implements hook_preprocess_hook().
 */
function dc_ajax_enhancements_preprocess_dc_ajax_shopping_cart(&$variables) {
  if ($variables['order']) {
    $variables['checkout_link']['attributes']['class'][] = 'form-submit';
    $variables['checkout_link']['attributes']['class'][] = 'btn';
    $variables['checkout_link']['attributes']['class'][] = 'checkout';

    $variables['checkout_url'] = l($variables['checkout_link']['text'], $variables['checkout_link']['path'], array(
      'attributes' => $variables['checkout_link']['attributes'],
      'query' => $variables['checkout_link']['query'],
      'fragment' => $variables['checkout_link']['fragment'],
      'html' => $variables['checkout_link']['html'],
    ));
  }
}

/**
 * Implements hook_library().
 */
function dc_ajax_enhancements_library() {
  $libraries['cart'] = [
    'title' => 'Site Cart',
    'version' => '1.0',
    'js' => array(
      drupal_get_path('module', 'dc_ajax_enhancements') . '/js/dc_ajax_enhancements.min.js' => array(
        'defer' => TRUE,
        'scope' => 'footer',
      ),
    ),
  ];

  return $libraries;
}
