<?php
/**
 * @file
 * Code for the Site Ingredients feature.
 */

include_once 'site_ingredients.features.inc';

/**
 * Implements hook_preprocess_node().
 */
function site_ingredients_preprocess_node(&$vars) {
  if ($vars['type'] == 'ingredient') {
    if ($vars['view_mode'] == 'line') {
      $vars['theme_hook_suggestions'][] = 'node__line';

      $body = $vars['body'][0]['value'];

      $vars['text'] = truncate_utf8($body, 150, $wordsafe = TRUE, $add_ellipsis = TRUE, $min_wordsafe_length = 5);

      $vars['image'] = field_view_field('node', $vars['node'], 'field_primary_image',
        array(
          'label' => 'hidden',
          'settings' => array(
            'image_style' => 'square_200x200',
          )
        )
      );
    }
  }
}
