<?php
/**
 * @file
 * Code for the Site Ingredients feature.
 */

include_once 'site_ingredients.features.inc';

/**
 * Implements hook_preprocess_node().
 */
function site_ingredients_preprocess_node(&$vars) {
  if ($vars['type'] == 'ingredient') {
    if ($vars['view_mode'] == 'line') {
      $vars['theme_hook_suggestions'][] = 'node__line';

      $body = $vars['body'][0]['value'];

      $vars['text'] = truncate_utf8($body, 150, TRUE, TRUE, 10);

      $image_arr = $vars['field_primary_image'][0];
      [$image_alt, $image_title] = site_general_get_alt_title($image_arr, $vars['title']);
      $image = site_general_make_lazy_img('square_500x500', $image_arr['uri'], $image_alt, $image_title);
      $vars['image'] = l($image, $vars['node_url'], array('html' => TRUE));
    }
  }
}
