<?php
/**
 * @file
 * Code for the Site Search feature.
 */

include_once 'site_search.features.inc';

/**
 * Implements hook_preprocess_page().
 */
function site_search_preprocess_page(&$vars) {
  drupal_add_library('site_search', 'site_search');
}

/**
 * Implements hook_library().
 */
function site_search_library() {
  $libraries['site_search'] = array(
    'title' => 'Site Search',
    'version' => '1',
    'js' => array(
      drupal_get_path('module', 'site_search') . '/js/site_search.js' => array(
        'defer' => TRUE,
        'scope' => 'footer',
      ),
    ),
    // 'dependencies' => [
    //   ['site_general', 'colorbox'],
    // ],
  );
  return $libraries;
}
