<?php

/**
 * @file
 * Code for the ajax add to cart enhancements.
 */

/**
 * Implements hook_theme().
 */
function instagram_block_enhancements_theme() {
  return [
    'instagram_block_image' => [
      'variables' => [
        'height' => NULL,
        'width' => NULL,
        'src' => NULL,
        'href' => NULL,
        'post' => NULL,
        'loading' => drupal_get_path('module', 'instagram_block_enhancements') . '/images/loading.gif',
      ],
      'template' => 'templates/instagram-block-image-enhancements',
    ],
  ];
}
