<?php
/**
 * @file
 * Code for the Site General feature.
 */

include_once 'site_general.features.inc';

/**
 * Implements hook_entity_info_alter().
 */
function site_general_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['square'] = array(
    'label' => t('Square Tile'),
    'custom settings' => FALSE,
  );
  $entity_info['node']['view modes']['line'] = array(
    'label' => t('Line Teaser'),
    'custom settings' => FALSE,
  );
  $entity_info['node']['view modes']['blog_teaser'] = array(
    'label' => t('Blog Teaser'),
    'custom settings' => FALSE,
  );
}

/**
 * Implements hook_preprocess_node().
 */
function site_general_preprocess_node(&$vars) {
  if ($vars['view_mode'] == 'square') {
    $vars['theme_hook_suggestions'][] = 'node__square';
    $node = $vars['node'];
    $type = $node->type;

    $image_arr = $vars['field_primary_image'][0];
    [$image_alt, $image_title] = site_general_get_alt_title($image_arr, $vars['title']);
    $vars['image'] = site_general_make_lazy_img('square_500x500', $image_arr['uri'], $image_alt, $image_title);
  }

  if ($vars['view_mode'] == 'blog_teaser') {
    $vars['theme_hook_suggestions'][] = 'node__blog_teaser';

    if (!empty($vars['field_primary_image'])) {
      $image_arr = $vars['field_primary_image'][0];
      [$image_alt, $image_title] = site_general_get_alt_title($image_arr, $vars['title']);
      $vars['image'] = site_general_make_lazy_img('square_500x500', $image_arr['uri'], $image_alt, $image_title);
    }
  }
}

/**
 * Implements hook_library().
 */
function site_general_library() {
  $libraries['colorbox'] = array(
    'title' => 'NTB Colorbox',
    'website' => 'https://github.com/jackmoore/colorbox',
    'version' => '1.6.4',
    'js' => array(
      libraries_get_path('colorbox') . '/jquery.colorbox-min.js' => array(
        'defer' => TRUE,
        'scope' => 'footer',
      ),
    ),
  );
  return $libraries;
}

/**
 * Description to help get alt and title tags
 * @param  arr $image    Info about an image.
 * @param  string $fallback Optional alt/title text option
 * @return arr Two strings of alt and title
 */
function site_general_get_alt_title($image, $fallback = '') {
  $alt = !empty($image['alt']) ? $image['alt'] : !empty($image['field_file_image_alt_text']) ? $image['field_file_image_alt_text'] : !empty($fallback) ? $fallback : 'naked truth beauty';
  $title = !empty($image['title']) ? $image['title'] : !empty($image['field_file_image_alt_text']) ? $image['field_file_image_alt_text'] : !empty($fallback) ? $fallback : 'naked truth beauty';
  return [$alt, $title];
}

function site_general_make_lazy_img($style, $uri, $alt, $title) {
  $url = image_style_url($style, $uri);

  $image = [
    'path' => drupal_get_path('theme', 'ntb') . '/images/loading.gif',
    'alt' => $alt,
    'title' => $title,
    'attributes' => [
      'data-src' => $url,
      'class' => ['lazy-img'],
    ],
  ];

  return theme('image', $image);
}
