<?php

/**
 * @file
 * NTB Commerce Customizations.
 */

 /**
  * Implements hook_form_alter().
  */
// function commerce_customizations_form_alter(&$form, &$form_state, $form_id) {
//   if ($form_id == 'commerce_checkout_form_checkout') {
//     $form['customer_profile_shipping']['commerce_customer_address'][LANGUAGE_NONE][0]['locality_block']['locality']['#attributes']['class'][] = 'form-control';
//     $form['customer_profile_shipping']['commerce_customer_address'][LANGUAGE_NONE][0]['locality_block']['administrative_area']['#attributes']['class'][] = 'form-control';
//     $form['customer_profile_shipping']['commerce_customer_address'][LANGUAGE_NONE][0]['locality_block']['postal_code']['#attributes']['class'][] = 'form-control';
//     $form['customer_profile_shipping']['commerce_customer_address'][LANGUAGE_NONE][0]['street_block']['thoroughfare']['#attributes']['class'][] = 'form-control';
//     $form['customer_profile_shipping']['commerce_customer_address'][LANGUAGE_NONE][0]['street_block']['premise']['#attributes']['class'][] = 'form-control';
//     $form['customer_profile_shipping']['commerce_customer_address'][LANGUAGE_NONE][0]['name_block']['name_line']['#attributes']['class'][] = 'form-control';
//     $form['customer_profile_shipping']['commerce_customer_address'][LANGUAGE_NONE][0]['country']['#attributes']['class'][] = 'form-control';
//
//     $form['customer_profile_billing']['commerce_customer_address'][LANGUAGE_NONE][0]['locality_block']['locality']['#attributes']['class'][] = 'form-control';
//     $form['customer_profile_billing']['commerce_customer_address'][LANGUAGE_NONE][0]['locality_block']['administrative_area']['#attributes']['class'][] = 'form-control';
//     $form['customer_profile_billing']['commerce_customer_address'][LANGUAGE_NONE][0]['locality_block']['postal_code']['#attributes']['class'][] = 'form-control';
//     $form['customer_profile_billing']['commerce_customer_address'][LANGUAGE_NONE][0]['street_block']['thoroughfare']['#attributes']['class'][] = 'form-control';
//     $form['customer_profile_billing']['commerce_customer_address'][LANGUAGE_NONE][0]['street_block']['premise']['#attributes']['class'][] = 'form-control';
//     $form['customer_profile_billing']['commerce_customer_address'][LANGUAGE_NONE][0]['name_block']['name_line']['#attributes']['class'][] = 'form-control';
//     $form['customer_profile_billing']['commerce_customer_address'][LANGUAGE_NONE][0]['country']['#attributes']['class'][] = 'form-control';
//
//     $form['account']['login']['mail']['#attributes']['class'][] = 'form-control';
//   }
//   elseif ($form_id == 'commerce_checkout_form_payment') {
//     $classes = ['number', 'owner', 'exp_month', 'exp_year', 'code'];
//
//     foreach ($classes as $class) {
//       $form['commerce_payment']['payment_details']['credit_card'][$class]['#attributes']['class'][] = 'form-control';
//     }
//
//     $inlines = ['exp_month', 'exp_year', 'code'];
//
//     foreach ($inlines as $inline) {
//       $form['commerce_payment']['payment_details']['credit_card'][$inline]['#attributes']['class'][] = 'form-inline';
//     }
//   }
// }

/**
 * Implements hook_form_element().
 */
function commerce_customizations_form_element($variables) {
  return theme_form_element($variables);
}

function commerce_customizations_commerce_checkout_pane_info_alter(&$checkout_panes) {
  $checkout_panes['commerce_payment_redirect']['locked'] = 0;
}

/**
 * Implements hook_entity_view_alter().
 */
function commerce_customizations_entity_view_alter(&$build, $type) {
  if ($type == 'commerce_order') {
    $order = $build['#entity'];

    $order_date = format_date($order->created);

    $markup = t('<div class="field-label">@email:</div>', array('@email' => 'Email'));
    $markup .= '<div class="field-items">' . $order->mail . '</div>';
    $markup .= t('<div class="field-label">@date:</div>', array('@date' => 'Order Date'));
    $markup .= '<div class="field-items">' . $order_date . '</div>';

    $build['email'] = array(
      '#prefix' => '<div class="field field-label-above">',
      '#suffix' => '</div>',
      '#type' => 'markup',
      '#markup' => $markup,
    );
  }
}
