<?php

/**
 * @file
 * Code for the Site Marquee feature.
 */

include_once 'site_marquee.features.inc';

/**
 * Implements hook_entity_info_alter().
 */
function site_marquee_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['slider'] = array(
    'label' => t('Slider'),
    'custom settings' => FALSE,
  );
}

/**
 * Implements hook_preprocess_node().
 */
function site_marquee_preprocess_node(&$vars) {
  if ($vars['type'] == 'marquee' && $vars['view_mode'] == 'slider') {
    $vars['theme_hook_suggestions'][] = 'node__slider';
    $image_url = $vars['field_marquee_image'][0]['uri'];
    $vars['image'] = image_style_url('marquee_large', $image_url);
    $vars['link'] = $vars['field_marquee_link'][0]['value'];

    // if (!empty($vars['field_marquee_hex'])) {
    //   $index = 0;
    //   foreach ($vars['field_marquee_hex'] as $key => $value) {
    //     $vars['hex' . $key] = $value['value'];
    //   }
    // }
  }
}

/**
 * Implements hook_preprocess_views_view().
 */
function site_marquee_preprocess_views_view(&$vars) {
  if ($vars['view']->name == 'marquee') {
    drupal_add_library('site_marquee', 'site_marquee');
  }
}

/**
 * Implements hook_library().
 */
function site_marquee_library() {
  $libraries['site_marquee'] = array(
    'title' => 'NTB Marquees',
    'version' => '1.0',
    'js' => array(
      drupal_get_path('module', 'site_marquee') . '/js/site_marquee.min.js' => array(
        'defer' => TRUE,
        'scope' => 'footer',
      ),
    ),
  );
  return $libraries;
}
