<?php
/**
 * @file
 * Code for the Site Marquee feature.
 */

include_once 'site_marquee.features.inc';

/**
 * Implements hook_entity_info_alter().
 */
function site_marquee_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['slider'] = array(
    'label' => t('Slider'),
    'custom settings' => FALSE,
  );
}

/**
 * Implements hook_preprocess_node().
 */
function site_marquee_preprocess_node(&$vars) {

  if ($vars['view_mode'] == 'slider') {
    $vars['theme_hook_suggestions'][] = 'node__slider';
    $image_url = $vars['field_marquee_image'][0]['uri'];
    $vars['image'] = file_create_url($image_url);
    $vars['link'] = $vars['field_marquee_link'][0]['value'];

    if (!empty($vars['field_marquee_hex'])) {
      $index = 0;
      foreach ($vars['field_marquee_hex'] as $key => $value) {
        $vars['hex' . $key] = $value['value'];
      }
    }
  }
}
