<?php

/**
 * @file
 * Code for the Site Products feature.
 */

include_once 'site_products.features.inc';

/**
 * Implements hook_menu().
 */
function site_products_menu() {
  $items = array();

  $items['ajax/shop/type/%'] = array(
    'page callback' => 'site_products_get_shop_view',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function site_products_return_tids($object) {
  if (!empty($object->tid)) {
    return $object->tid;
  }
  else {
    return NULL;
  }
}

/**
 * AJAX callback shop view.
 *
 * @param string $term
 *   The taxonomy term to filter with.
 */
function site_products_get_shop_view($term) {
  $tids = [];
  $tid = NULL;
  $vocabs = taxonomy_vocabulary_get_names();
  $vid = $vocabs['product_types']->vid;
  $tree = taxonomy_get_tree($vid);
  $tids = array_map('site_products_return_tids', $tree);
  $terms = taxonomy_term_load_multiple($tids);

  foreach ($terms as $key => $taxonomy) {
    $alias = $taxonomy->field_url[LANGUAGE_NONE][0]['value'];

    if ($alias == $term) {
      $tid = $key;
      break;
    }
  }

  $view = views_get_view('shop');
  $view->set_display('block_no_filter');
  $view->add_item($view->current_display, 'filter', 'field_data_field_product_type', 'field_product_type_tid', array('value' => $tid, 'group' => 1));
  $view->pre_execute();
  $view->execute();
  print $view->render();
}

/**
 * Implements hook_entity_info_alter().
 */
function site_products_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['product'] = array(
    'label' => t('Product'),
    'custom settings' => FALSE,
  );

  $entity_info['node']['view modes']['add_to_cart'] = array(
    'label' => t('Add to Cart'),
    'custom settings' => FALSE,
  );
}

/**
 * Implements hook_preprocess_views_view().
 */
function site_products_preprocess_views_view(&$vars) {
  if ($vars['view']->name == 'shop') {
    drupal_add_js(libraries_get_path('jquery-match-height') . '/dist/jquery.matchHeight-min.js');
    drupal_add_js(drupal_get_path('module', 'site_products') . '/js/site_shop.js');
  }
}

/**
 * Implements hook_node_view().
 */
function site_products_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'product_display' && $view_mode == 'full') {
    $node->content['#attached']['js'][] = drupal_get_path('module', 'site_products') . '/js/site_products.js';
  }
}
