<?php
/**
 * @file
 * Code for the Site Products feature.
 */

include_once 'site_products.features.inc';

/**
 * Implements hook_entity_info_alter().
 */
function site_products_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['product'] = array(
    'label' => t('Product'),
    'custom settings' => FALSE,
  );

  $entity_info['node']['view modes']['add_to_cart'] = array(
    'label' => t('Add to Cart'),
    'custom settings' => FALSE,
  );
}

/**
 * Implements hook_preprocess_page().
 */
function site_products_preprocess_page(&$vars) {
  drupal_add_js(libraries_get_path('jquery-throttle-debounce') . '/jquery.ba-throttle-debounce.min.js');
  drupal_add_js(libraries_get_path('jquery-match-height') . '/dist/jquery.matchHeight-min.js');
  drupal_add_js(drupal_get_path('module', 'site_products') . '/js/site_products.js');
}

/**
 * Implements hook_preprocess_node().
 */
function site_products_preprocess_node(&$vars) {
  if ($vars['type'] == 'product_display') {
    // dpm($vars);
  }
}
