<?php

/**
 * Implements hook_page_attachments_alter().
 */
// function ntb_sw_preprocess_page(&$variables) {
  // xdebug_break();
// // function ntb_sw_page_attachments_alter(&$attachments) {
//   $attachments['#attached']['library'][] = 'sw_dcp/serviceworker';
//   $manifest = array(
//     '#type' => 'html_tag',
//     '#tag' => 'link',
//     '#attributes' => array(
//       'rel' => 'manifest',
//       'href' => '/manifest.json',
//     ),
//   );
//   $attachments['#attached']['html_head'][] = [$manifest, 'manifest'];
// }

/**
 * Implements hook_preprocess_page().
 */
function ntb_sw_preprocess_page(&$vars) {
  drupal_add_library('ntb_sw', 'sw');
}

/**
 * Implements hook_library().
 */
function ntb_sw_library() {
  $libraries['sw'] = array(
    'title' => 'NTB Service Worker',
    'version' => '1.0',
    'js' => array(
      drupal_get_path('module', 'ntb_sw') . '/js/ntb_sw.js' => array(),
    ),
  );
  return $libraries;
}
