<?php

/**
 * @file
 * Module file for ntv service worker.
 */

/**
 * Implements hook_preprocess_page().
 */
function ntb_sw_preprocess_page(&$vars) {
  drupal_add_library('ntb_sw', 'sw');
}

/**
 * Implements hook_library().
 */
function ntb_sw_library() {
  $libraries['sw'] = array(
    'title' => 'NTB Service Worker',
    'version' => '1.0',
    'js' => array(
      drupal_get_path('module', 'ntb_sw') . '/js/ntb_sw.js' => array(),
    ),
  );
  return $libraries;
}
