<?php

/**
  * Implements hook_theme_registry_alter().
*/
function ntb_lazy_img_theme_registry_alter(&$theme_registry) {
  if (!empty($theme_registry['image'])) {
    $theme_registry['image']['preprocess functions'][] = 'ntb_lazy_img_image_preprocess';
  }
}

/**
* Implements hook_preprocess_HOOK().
*/
function ntb_lazy_img_image_preprocess(array &$variables, string $hook) {
  if (variable_get('ntb_lazy_img', TRUE) && !path_is_admin(current_path())) {
    // Ony lazy loaded image style based files.
    if (valid_url($variables['path'], TRUE) && !empty($variables['style_name'])) {
      $variables['attributes']['data-src'] = $variables['path'];
      $variables['attributes']['loading'] = "lazy";
      $variables['path'] = drupal_get_path('theme', 'ntb') . '/images/loading.svg';
      $variables['attributes']['class'][] = 'lazy-img';
    }
  }
}
